### ISSUE TITLE
qgLikelihood Issue

### ISSUE THREAD

**Issue by caleb-james-smith** [CMSDASAtLPC/LongExerciseSusyTopTag#27]
Problem with qgLikelihood seen... for the moment we commented out the QGL variables in TopTagger_custom.cfg to avoid this issue. I recall this issue from last year, but I don't remember the better fix. 

```
[rkim@cmslpc116 LongExerciseSusyTopTag]$ ./RunSimpleAnalyzer -I TTbarNoHad
Running over sampleset TTbarNoHad
Found 3 file summaries
Starting loop for TTbarSingleLepT
At event 0
/uscms_data/d3/rkim/CMSDAS2021/SUSYTopTagging/CMSSW_9_3_3/src/TopTagger/TopTagger/test/../..//TopTagger/src/Constituent.cpp:114, in function "getExtraVar" -- ExtraVar: qgLikelihood not found!!!
terminate called after throwing an instance of 'TTException'
Aborted
```

**Comment by kpedro88** [comment]
@caleb-james-smith the fix from last year was https://github.com/susy2015/TopTagger/commit/9e03fa496e4dd13fb51fbd8296871565983bc333, but I'm not sure if this is the same issue

**Comment by caleb-james-smith** [comment]
Fix: https://github.com/CMSDASAtLPC/LongExerciseSusyTopTag/pull/28

**Comment by caleb-james-smith** [comment]
@kpedro88 thanks, maybe that is one of the issues from last year that I am thinking of... though this new issue also may have happened last year but was not updated in the repo
